name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t "${DOCKERHUB_USERNAME}"/meme-gen:latest .
      - name: Login to DockerHub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Push Docker Image to DockerHub
        run: docker push "${DOCKERHUB_USERNAME}"/meme-gen:latest
      - name: Start Minikube
        run: |
          minikube start --force --driver=docker.io
          snap install kubectl --classic
      - name: Deploy to Kubernetes
        uses: steebchen/kubectl@v1.0.0
        with:
          kubeconfig: ${{ env.KUBECONFIG }}
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
